name: SBOM upload

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  SBOM-upload:

    runs-on: ubuntu-slim
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: Generate SBOM
      run: |
        curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b $RUNNER_TEMP
        $RUNNER_TEMP/syft scan dir:./ -o spdx-json=sbom.spdx.json
    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: sbom
        path: sbom.spdx.json
    - name: SBOM upload
      uses: advanced-security/spdx-dependency-submission-action@5530bab9ee4bbe66420ce8280624036c77f89746 # v0.1.1
